### PR TITLE
Fix Markdown issues by switching the parser to Marked

### PR DESCRIPTION
**Pull request by chase**
The official [Github-Flavored-Markdown](https://npmjs.org/package/github-flavored-markdown) uses a very old (at the time of writing, _9 months_) version of Showdown.js.

This may not seem like a problem, however when using GitHub-style code blocks, odd results can appear.

An example is when using a code block with `coffeescript` explicitly stated as the language in a Markdown document, any of the code that has two successful newlines `\n` will embed a `pre code` element inside of the `div.highlight pre` element where the rest of the code resides.

Not only does [Marked](https://github.com/chjj/marked) properly support GFM, but it is also currently the fastest Javascript parser for Markdown. It is well maintained and should provide a much more stable library as it is actively receiving contributions.

### CODE REVIEW

**Comment by balupton** [comment]
Hi @Chase, this is awesome! Glad to finally move away from the old library we are currently using.

One issue is that having `sanitize` equal to `true` produces different output that what we are currently expecting.

However, even with `sanitze` set to `false` that change to code blocks is one that cannot be avoided, which would mean people's current stylings and probably the pygments plugin would run into issues when they install this plugin's new version.

What I'm thinking we should do is release this as a new `marked` plugin, and then just deprecate the current `markdown` plugin. Your thoughts?

**Comment by balupton** [comment]
Published to `docpad-plugin-marked` and updated the pygments plugin as well. Pushed to the `dev` branch. Will push to `master` and `docpad-6.x` branches once I update the skeletons and wiki etc to reflect this change.

**Comment by chase** [comment]
Sounds great to me! Pismute also has an interesting take on the plugin, that I think is worth checking out.

Also, [chase/docpad-plugin-highlightjs](/chase/docpad-plugin-highlightjs) provides a pure JavaScript alternative to Pygments.
I've already added it to NPM and I don't mind being the maintainer, so no need to merge it.
I just thought that you might want to link to it to let users know it is a decent alternative.

**Comment by balupton** [comment]
Sweet, so I've published a new version of the markdown plugin indicating the deprecation and updated the skeletons that I have write access to. I've also updated the plugins page to reflect these changes and to include highlightjs there https://github.com/bevry/docpad/wiki/Plugins

If you're up for it, we can get the highlightjs plugin into the the docpad-extras repo and both be maintainers for it if you'd like? I'd give you write access to the docpad-extras repo of course.

**Comment by chase** [comment]
Feel free to merge it!
Once you get the highlightjs plugin into the docpad-extras repo, I'll update my repo's README to forward to it and add you as an owner in the NPM registry.

As a side note, once I get some more time I'll be working on [a static tag index](/chase/docpad-plugin-tagdex) that may prove useful for static blogs using DocPad.
Hopefully I will be able to contribute to DocPad beyond a plugin or two in the near future.

**Pull request merged**
