### PR TITLE
`docpad` was undefined, changed params and used new DocPad's helper func...

### PR DESCRIPTION
**Pull request by DjebbZ**
...tions.

In an first attempt to update the rest plugin to Docpad 6, I noticed that the `serverAfter` event is emitted with the `server` param, whereas the rest plugin receives a `{docpad,server}` param. So using it produces as is produces this error (when issueing `docpad server`) :

``` shell
$  docpad server
info: Welcome to DocPad v6.0.2
info: DocPad listening to http://localhost:9778/ on directory /Users/khalid_jebbari/Documents/Javascript/test-rest-docpad/out
error: Something went wrong with the action
error: An error occured: Cannot read property 'server' of undefined TypeError: Cannot read property 'server' of undefined
    at RestPlugin.serverAfter (/Users/khalid_jebbari/Documents/Javascript/test-rest-docpad/node_modules/docpad-plugin-rest/out/rest.plugin.js:22:15)
    at /Users/khalid_jebbari/node/lib/node_modules/docpad/out/lib/plugin.js:43:34
    at /Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/events.js:250:18
    at _Class.runTask (/Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/flow.js:265:9)
    at _Class.nextTask (/Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/flow.js:257:14)
    at _Class.run (/Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/flow.js:278:18)
    at _Class.sync (/Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/flow.js:301:12)
    at DocPad.emitSync (/Users/khalid_jebbari/node/lib/node_modules/docpad/node_modules/bal-util/out/lib/events.js:253:13)
    at /Users/khalid_jebbari/node/lib/node_modules/docpad/out/lib/docpad.js:2061:23
    at _Class.next (/Users/khalid_jebbari/node/lib/node_modules/docpad/out/lib/docpad.js:2171:24)

```

So I thought of changing the param to `{docpad}` only, requiring a small change in docpad itself (posting it in a few minutes). With these 2 changes, others errors were happening because 'server' isn't a property of docpad. So I update the plugin code to match the new API and use DocPad's helpers, and all errors disappeared when issueing a `docpad server`.

But I couldn't test it to make sure it works properly. For a reason I can't explain, this very small [gist](https://gist.github.com/2917870) with code to test a basic POST request to the server doesn't work, telling me `Cannot find module 'request'`, whereas I do have request installed globally...

### CODE REVIEW

**Comment by balupton** [comment]
Closing.

It is correct the `docpad` was undefined, as as of DocPad v5 it is now accessed via `@docpad` inside plugins, instead being passed as an option. `server` should be passed as an argument, as it is what that event is for.

To clarify, the solution is to remove the docpad argument, and use `docpad = @docpad` instead.

**Comment by DjebbZ** [comment]
Ok, didn't know about `@docpad`. Thanks for the clarification.

**Comment by stegrams** [comment]
Hello @balupton 

I like the idea of a quick and dirty RESTful interface with DocPad and permanently storage in generated files. These days I learn Backbone and I tried to set DocPad with rest plugin as server side but it was not feasable for a newbie like me even after some changes I made to the plugins code.

In particular I d like to send a post request to change a documents metadata and then generate this document as JSON file (permanent storage)

I m not sure if this is a realistic expectation from a static content generator but I would like to see an example of this or something similar

**Comment by balupton** [comment]
@stegrams see https://github.com/docpad/docpad-plugin-nativecomments and https://github.com/lzrski/docpad-plugin-json for working example of what you've asked. You'll be able to use that principle to accomplish whatever you're after. So yeah, it is an expectation we have for DocPad :)

**Pull request closed without merging**
