### PR TITLE
docpad-plugin-uglify

### PR DESCRIPTION
**Pull request by georgeOsdDev**
Hello balupton.
I create new docpad plugin using [UglifyJs](https://github.com/mishoo/UglifyJS).
This plugin compress .js files when docpad start `renderDocument`

### CODE REVIEW

**Comment by balupton** [comment]
Hey George, awesome work. Happy to get this promoted. Lets leaves this in your repo for the time being, until https://github.com/bevry/docpad-extras/issues/27 has completed :)

**Comment by georgeOsdDev** [comment]
HI Balupton. Thank you for announcement :)

**Comment by balupton** [comment]
Pulled and pushed to https://github.com/docpad/docpad-plugin-uglify

**Comment by georgeOsdDev** [comment]
Hi Blaupton,Thank you for marge.
I have one question about NPM publish.
I have not published this plugin to NPM yet.So is it better to reedit package.json about git repository and regist to NPM?
IF you have any Docpad's policy about plugin's package.json, I will follow.
Thanks.

**Pull request merged**
