### PR TITLE
Highlight.js Plugin as Submodule

### PR DESCRIPTION
**Pull request by chase**
Regarding chase/docpad-plugin-highlightjs#4

Instead of merging to `bevry/docpad-extras`, I believe adding the `chase/docpad-plugin-highlightjs` repository as a submodule would be more beneficial.

The main benefit is that you still have control over which of my updates make it into `bevry/docpad-extras` while I am still able to freely update the plugin. This will avoid heavy use of the `dev` branch and simplify any merge processes.

Another benefit is that notifications I receive will only pertain to the plugins which I maintain, allowing me to more easily focus on the Highlight.js plugin.

There are [a few caveats to Submodules](http://git-scm.com/book/en/Git-Tools-Submodules), mainly a few issues about pulling updates into the repository.

You can also [automatically init and update on fetch and pull](http://hedgehogshiatus.com/git-submodules-automatic-init-and-update-on-f-69372) if you prefer.

### CODE REVIEW

**Comment by balupton** [comment]
Hey Chase,

Thanks for this :) I'm a bit reluctant to go ahead with the submodule route due to past experience, though still open to it. We used submodules for the plugin repository with Aloha Editor for about 6 months, and everyone came to hating it due to the increased complexity, always ensure we are on a correct working tree, assigning the permissions to the correct source repository, merging in changes and getting them published to the shared repo, all become a lot more difficult - in the end Aloha Editor actually just merged all the plugins directly into the same repo as we do here.

The problem with being notified about changes that do not affect you, would be fixable by changing the docpad-extras watch status to "not watching". Which would allow you to just get notifications when you are mentioned or on topics you've posted on.

Keen to hear your thoughts?

**Comment by chase** [comment]
While I understand that Git can make things difficult when using submodules, the newer versions of Git have vastly improved the cloning of projects with submodules. Recursion is the new default.
Also, permissions and pull requests are a non-issue: you will be added as a contributor and any further pull requests can be handled by either you or myself.

In comparison to what I found in Aloha Editor's monolithic repository structure, DocPad is primarily decentralized. DocPad's main repository is separate from the Extras and are maintained independently. Extras are generally installed using NPM from what I can tell, as such I don't entirely understand the point of the docpad-extras repository aside from a listing for available modules.
It is likely that I'm missing the true reason for the repository, as I haven't read through all of DocPad's code at this point.

As well as that system of notifications might work, new issues that have not been brought to my attention by the person posting the issue or by yourself will likely go unnoticed. I simply have too many notifications as it is and wish to manage them in an effective manner.

I apologize if this comes off as a rather rigid or abrasive response, so if it comes down to unnecessary complexity then the submodule can always be turned into a plain, merged directory by removing the `.gitmodules` entry after the it is initiated and updated.

Thank you.

**Comment by balupton** [comment]
Hi Chase,

> It is likely that I'm missing the true reason for the repository, as I haven't read through all of DocPad's code at this point.

The centralised structure of the extras instead of plenty of repos, is so we can:
1. easily run automated tests against them when each new docpad version is released to make sure it is all fine and dandy
2. easily have all of the team being able to easily maintain (edit the source and publish new versions) all the official plugins, instead of having to rely on an external user to pull in changes and publish the new version
3. easily be able to add new users to the team (github organization and as npm maintainers) rather than having to wait on external users to update their contributor list

It is all towards making it as easy as possible to have the entire trusted team members able to test, update, publish, and deploy new versions of the plugins as quickly and easily as possible - rather than being dependent on an external factor we can't control, and would cause timely delays in the workflow (as there would always be a waiting period on the external person - the length could be a day, to even permanent).

For instance, with your submodule suggestion - how would that help with points 2 and 3 above?

**Comment by chase** [comment]
Benjamin,

Thank you for the prompt and helpful response!

Considering the circumstances you mentioned, I agree that your approach will be best in the long run.

I am closing this pull request, feel free to merge the repository.

When I have time tomorrow, I will add your access privileges to the NPM registry.

**Pull request closed without merging**
