### PR TITLE
Adding support for Handlebars

### PR DESCRIPTION
**Pull request by mmoulton**
Here is a plugin to support the Handlebars template language (an extension of Mustache).

See: http://handlebarsjs.com for more info on the language.

### CODE REVIEW

**Comment by mmoulton** [comment]
Looks like you merged docpad-6.x into master. If you plan on accepting this pull I can resubmit against master if it would be helpful. If not, no problem, I will release this outside of docpad-extras.

**Comment by balupton** [comment]
Published :) Post back with your npm user email, and I'll add you as an owner of the plugin so you can update it too.

**Comment by mmoulton** [comment]
Thanks. npm email is mike at meltmedia dot com

**Comment by balupton** [comment]
You don't exist

```

$ npm owner add mike@meltmedia.com docpad-plugin-handlebars
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:mike@meltmedia.com
npm http 404 https://registry.npmjs.org/-/user/org.couchdb.user:mike@meltmedia.com
npm ERR! Error getting user data for mike@meltmedia.com

npm ERR! Error: not_found missing: -/user/org.couchdb.user:mike@meltmedia.com
npm ERR!     at Request._callback (/Users/balupton/.nvm/v0.6.15/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:183:12)
npm ERR!     at Request.callback (/Users/balupton/.nvm/v0.6.15/lib/node_modules/npm/node_modules/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/Users/balupton/.nvm/v0.6.15/lib/node_modules/npm/node_modules/request/main.js:605:16)
npm ERR!     at Request.emit (events.js:67:17)
npm ERR!     at IncomingMessage.<anonymous> (/Users/balupton/.nvm/v0.6.15/lib/node_modules/npm/node_modules/request/main.js:564:14)
npm ERR!     at IncomingMessage.emit (events.js:88:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:137:23)
npm ERR!     at CleartextStream.ondata (http.js:1150:24)
npm ERR!     at CleartextStream._push (tls.js:375:27)
npm ERR!     at SecurePair.cycle (tls.js:734:20)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Darwin 11.4.0
npm ERR! command "node" "/Users/balupton/.nvm/v0.6.15/bin/npm" "owner" "add" "mike@meltmedia.com" "docpad-plugin-handlebars"
npm ERR! cwd /Users/balupton/Dropbox/Projects
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.16
npm ERR! message not_found missing: -/user/org.couchdb.user:mike@meltmedia.com
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/balupton/Dropbox/Projects/npm-debug.log
npm not ok
$ 

```

**Comment by balupton** [comment]
Okay, it actually needs the npm username, not email. My bad. So what's your npm username?

**Comment by mmoulton** [comment]
No worries. My username is 'mmoulton'

Thanks!

On Jun 22, 2012, at 3:08 AM, Benjamin Arthur Lupton
reply@reply.github.com
wrote:

**Comment by balupton** [comment]
Done :)

**Pull request merged**
