### PR TITLE
Added a basic proxy plugin

### PR DESCRIPTION
**Pull request by ncrohn**
I put in support for a very basic proxy plugin using the request package.

### CODE REVIEW

**Comment by balupton** [comment]
Wow. This totally slipped past me. Will merge in!

**Comment by balupton** [comment]
Can you elaborate a bit more about what this plugin does in its readme file? From first glance, it also seems it should be possible to write some automated tests for this.

Keen to hear your thoughts :)

**Comment by ncrohn** [comment]
Absolutely, I'll add in some more information to the plugin readme and get some basic tests in there.

**Comment by balupton** [comment]
Pulled and pushed to https://github.com/docpad/docpad-plugin-proxy

**Pull request merged**
