### PR TITLE
Added html5-boilerplate-jade-less-livereload.docpad to exchange.

### PR DESCRIPTION
**Pull request by jh3y**
Added a new skeleton which uses the HTML5 boilerplate but uses Jade and LESS for file rendering.

### CODE REVIEW

**Comment by balupton** [comment]
Awesome. Two questions:
- Why have a `_docpad.js` file?
- Why is there a `src/less` folder?

Ideally, we'd like to get official skeletons as streamlined as possible. As people will be using them as references for best practices. Having the two above points is likely to confuse.

That being said, a lot of people struggle with jade, so it is great that more people are taking the initiative to provide jade skeletons :) Keep up the great work.

**Comment by jh3y** [comment]
Hey @balupton 

Thanks for the quick feedback!

I'm relatively new to docpad but I am really enjoying using it hence wanting to contribute. 

I was told that _docpad.js was used to solve a compatibility issue with Windows but if this is no longer the case then I am quite happy to take this out and you are right it will make it much less confusing.

As per my less directory. Do you have any suggestions as to where to let this sit. My thinking was that having a less directory containing all the various less files for different components across a site which are then merged together outside of the output directory and then pushed up would be the way to go. I had some issues with rendering when my less files were with the 'files' directory. I simply adopted this approach to make my sites as modular as possible. For example, a jade template for say the header, footer, and body but then also less files for each of those which then merge into the core.css for the site.

I'd very much like to get any changes you request in so that I can make this an official skeleton.

Thanks for getting back to me.

@jheytompkins

**Comment by jh3y** [comment]
Made changes. Streamlined in line with your comments now. Hopefully this can get pushed in and become an official skeleton.

@jheytompkins

**Comment by balupton** [comment]
Merged :) :rocket:

**Comment by jh3y** [comment]
Thanks :)

**Comment by jh3y** [comment]
Will this make it's way on to the site? :)

**Comment by balupton** [comment]
Yep, next regeneration of the site it will be there :)

**Comment by jh3y** [comment]
Sweet :)

**Pull request merged**
